
services:

  monorepo_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: monorepo_base #give the base image a name.
    command: "true" #keep the image from running immediately.


  nginx:
    image: nginx:latest
    container_name: nginx
    ports: ["80:80"]
    extra_hosts: ["e7270:100.123.122.115"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common_proxy_headers.conf:/etc/nginx/common_proxy_headers.conf
    depends_on:
      - netdata
      - melange_home
      - melange_streams
      - melange_health
      - melange_dbone
      - melange_logs
      - melange_alerts
      - melange_telegram
      - stocks_ticks
      - stocks_candles
      - stocks_dynamic_candles
      - stocks_ticking

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    pid: host
    restart: unless-stopped
    ports:
      - "19999:19999"  # Netdata Web UI
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    volumes:
      - netdata_config:/etc/netdata
      - netdata_lib:/var/lib/netdata
      - netdata_cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  netdata_config:
  netdata_lib:
  netdata_cache:

networks:
  default:
    name: algo

include:
  - ./s_melange/melange-docker-compose.yml
  - ./s_stocks/stocks-docker-compose.yml
