
services:

  monorepo_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: monorepo_base #give the base image a name.
    command: "true" #keep the image from running immediately.


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    extra_hosts:
      - "mbp:100.103.219.96"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common_proxy_headers.conf:/etc/nginx/common_proxy_headers.conf
    depends_on:
      - melange_test1
      - stocks_test2

networks:
  default:
    name: algo

include:
  - ./s_melange/docker-compose.yml
  - ./s_stocks/docker-compose.yml