
services:

  monorepo_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: monorepo_base #give the base image a name.
    command: "true" #keep the image from running immediately.


  nginx:
    image: nginx:latest
    container_name: nginx
    ports: ["80:80"]
    extra_hosts: ["e7270:100.123.122.115"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common_proxy_headers.conf:/etc/nginx/common_proxy_headers.conf
    depends_on:
      - melange_home
      - melange_streams
      - melange_health
      - melange_dbone
      - melange_logs
      - melange_alerts
      - melange_telegram
      - stocks_ticks
      - stocks_candles
      - stocks_dynamic_candles
      - stocks_ticking

networks:
  default:
    name: algo

include:
  - ./s_melange/melange-docker-compose.yml
  - ./s_stocks/stocks-docker-compose.yml
