
services:

  monorepo_base:
    build:
      context: .
      dockerfile: Dockerfile_base
    image: monorepo_base #give the base image a name.
    command: tail -f /dev/null
    env_file:
      - .env


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "5080:5080"
    extra_hosts: ["t5810:100.86.138.85"]
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/common_proxy_headers.conf:/etc/nginx/common_proxy_headers.conf
      - ./nginx/static:/usr/share/nginx/html

    depends_on:
      - melange_api_gateway

networks:
  default:
    external: true
    name: algo

include:
  - ./s_melange/melange-docker-compose.yml
  - ./s_stocks/stocks-docker-compose.yml
  - ./s_brokers/brokers-docker-compose.yml