
services:

  melange_service_status:
    image: monorepo_base
    container_name: melange_service_status
    restart: always
    networks: [default]
    volumes:
      - ./service_status:/app
      - ../common:/app/common
    command: ["python", "service_status.py"]

  melange_api_gateway:
    image: monorepo_base
    container_name: melange_api_gateway
    restart: always
    ports: [ "5009:5009" ]
    networks: [ default ]
    volumes:
      - ./api_gateway:/app
      - ../common:/app/common
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["python", "start.py"]

  melange_docker_scheduler:
    image: monorepo_base
    container_name: melange_docker_scheduler
    restart: always
    networks: [ default ]
    volumes:
      - ./docker_scheduler:/app
      - ../common:/app/common
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: [ "python", "docker_scheduler.py" ]


  melange_dev_api:
    image: monorepo_base
    container_name: melange_dev_api
    restart: always
    ports: [ "5010:5010" ]
    networks: [ default ]
    volumes:
      - ./dev_api:/app
      - ../common:/app/common
    command: [ "python", "start.py" ]
