
services:


  melange_alerts:
    build: ./alerts
    container_name: melange_alerts
    restart: always
    ports: ["5006:5006"]
    networks: [default]
    volumes:
      - ./alerts:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5006
    depends_on:
      - monorepo_base

  melange_service_status:
    build: ./service_status
    container_name: melange_service_status
    restart: always
    networks: [default]
    volumes:
      - ./service_status:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

  melange_api_gateway:
    build: ./api_gateway
    container_name: melange_api_gateway
    restart: always
    ports: [ "5009:5009" ]
    networks: [ default ]
    volumes:
      - ./api_gateway:/app
      - ../common:/app/common
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - monorepo_base