
services:

  melange_home:
    build: ./home
    container_name: melange_home
    restart: always
    ports: ["5001:5001"]
    networks: [default]
    volumes:
      - ./home:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5001
    depends_on:
      - monorepo_base

  melange_health:
    build: ./health
    container_name: melange_health
    restart: always
    ports: ["5003:5003"]
    networks: [default]
    volumes:
      - ./health:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5003
    depends_on:
      - monorepo_base

  melange_logs:
    build: ./logs
    container_name: melange_logs
    restart: always
    ports: [ "5005:5005" ]
    networks: [ default ]
    volumes:
      - ./logs:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GUNICORN_BIND=0.0.0.0:5005
    depends_on:
      - monorepo_base

  melange_alerts:
    build: ./alerts
    container_name: melange_alerts
    restart: always
    ports: ["5006:5006"]
    networks: [default]
    volumes:
      - ./alerts:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5006
    depends_on:
      - monorepo_base

  melange_telegram:
    build: ./telegram
    container_name: melange_telegram
    restart: always
    ports: ["5007:5007"]
    networks: [default]
    volumes:
      - ./telegram:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5007
    depends_on:
      - monorepo_base

  melange_docker_db:
    build: ./docker_db
    container_name: melange_docker_db
    restart: always
    ports: ["5008:5008"]
    networks: [default]
    volumes:
      - ./docker_db:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GUNICORN_BIND=0.0.0.0:5008
    depends_on:
      - monorepo_base