
services:

  stocks_ticks:
    build: ./ticks
    container_name: stocks_ticks
    restart: always
    networks: [default]
    volumes:
      - ./ticks:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base
  
  stocks_candles:
    build: ./candles
    container_name: stocks_candles
    restart: always
    networks: [default]
    volumes:
      - ./candles:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

  stocks_dynamic_candles:
    build: ./dynamic_candles
    container_name: stocks_dynamic_candles
    restart: always
    networks: [default]
    volumes:
      - ./dynamic_candles:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base
