
services:

  stocks_ticks:
    image: monorepo_base
    container_name: stocks_ticks
    restart: always
    networks: [default]
    volumes:
      - ./ticks:/app
      - ../common:/app/common
    command: ["python", "ticks.py"]

  
  stocks_candles:
    image: monorepo_base
    container_name: stocks_candles
    restart: always
    networks: [default]
    volumes:
      - ./candles:/app
      - ../common:/app/common
    command: ["python","candles.py"]


  stocks_dynamic_candles:
    image: monorepo_base
    container_name: stocks_dynamic_candles
    restart: always
    networks: [default]
    volumes:
      - ./dynamic_candles:/app
      - ../common:/app/common
    command: ["python", "dynamic_candles.py"]

