
services:

  stocks_ticks:
    build: ./ticks
    container_name: stocks_ticks
    restart: always
    networks: [default]
    volumes:
      - ./ticks:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base
  
  stocks_candles:
    build: ./candles
    container_name: stocks_candles
    restart: always
    networks: [default]
    volumes:
      - ./candles:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

  stocks_dynamic_candles:
    build: ./dynamic_candles
    container_name: stocks_dynamic_candles
    restart: always
    networks: [default]
    volumes:
      - ./dynamic_candles:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

  stocks_ticking:
    build: ./ticking
    container_name: stocks_ticking
    restart: always
    ports: ["5024:5024"]
    networks: [default]
    volumes:
      - ./ticking:/app
      - ../common:/app/common
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5024
    depends_on:
      - monorepo_base

  stocks_dash_charts:
    build: ./dash_charts
    container_name: stocks_dash_charts
    restart: always
    ports: [ "5025:5025" ]
    networks: [ default ]
    volumes:
      - ./dash_charts:/app
      - ../common:/app/common
      - ../s_stocks/spreads:/app/s_stocks/spreads
      - C:/Users/Sharad/OneDrive/Algo/screener/parquet:/app/parquet
      - ../gunicorn_config.py:/app/gunicorn_config.py
    environment:
      - GUNICORN_BIND=0.0.0.0:5025
    depends_on:
      - monorepo_base