
services:

  brokers_api_tokens:
    build: ./api_tokens
    container_name: brokers_api_tokens
    restart: always
    networks: [default]
    volumes:
      - ./api_tokens:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

  brokers_bypass:
    build: ./bypass
    container_name: brokers_bypass
    restart: always
    networks: [ default ]
    volumes:
      - ./bypass:/app
      - ../common:/app/common
    depends_on:
      - monorepo_base

