
services:

  brokers_api_tokens:
    image: monorepo_base
    container_name: brokers_api_tokens
    restart: always
    networks: [default]
    volumes:
      - ./api_tokens:/app
      - ../common:/app/common
      - ../common_library:/app/common_library
    command: ["python", "api_token.py"]

  brokers_bypass:
    image: monorepo_base
    container_name: brokers_bypass
    restart: always
    networks: [ default ]
    volumes:
      - ./bypass:/app
      - ../common:/app/common
      - ../common_library:/app/common_library
    command: ["python", "bypass.py"]

