"MBP.local":
  profiles:
    fa97273: 'profile 5'
    fa222351: 'profile 4'
    ylcgn: 'profile 5'
    sivdu: 'profile 4'
    ym3006: 'Default'
    rs5756: 'profile 1'
    mim066: 'profile 2'

"MBA.local":
  profiles:
    fa97273: 'profile 5'
    fa222351: 'profile 3'
    ylcgn: 'profile 5'
    sivdu: 'profile 3'
